# Assignment #1 Linear Algebra - Python
## By Wejdan Al-Ahmadi
<hr style="border:2px solid gray"> </hr>

### Linear Algebra

Use your Jupyterlab environment and NumPy to solve the attached systems of equations. What values do you get for x,y, and z?

<hr style="border:0.5px solid gray"> </hr>

### Equation #1

3x + 5y = 6

7x - 5y = 9

In [1]:
import numpy as np

In [2]:
#coeficients
A1 = np.array([[3,5],[7,-5]])

#Requirement
B1 = np.array([[6],[9]])

In [3]:
# Solving the problem
X1 = np.linalg.inv(A1).dot(B1)
X1

array([[1.5],
       [0.3]])

In [4]:
#Checking our results by plugging in the values
x1 = X1[0][0]
y1 = X1[1][0]

In [5]:
# check 3x + 5y = 6
3*x1 + 5*y1

6.0

In [6]:
# check 7x - 5y = 9
7*x1 - 5*y1

9.0

<hr style="border:0.5px solid gray"> </hr>

### Equation #2

 x + y + z = 6

    y + z = -4

2x + 5y - z = 27

In [7]:
#coeficients
A2 = np.array([[1,1,1],[0,1,1],[2,5,-1]])

#Requirement
B2 = np.array([[6],[-4],[27]])

In [8]:
# Solving the problem
X2 = np.linalg.inv(A2).dot(B2)
X2

array([[10. ],
       [ 0.5],
       [-4.5]])

In [9]:
#Checking our results by plugging in the values
x2 = X2[0][0]
y2 = X2[1][0]
z2 = X2[2][0]

In [10]:
# check  x + y + z = 6
1*x2 + 1*y2 + 1*z2

6.000000000000002

In [11]:
# check y + z = -4
1*y2 + 1*z2

-4.0

In [12]:
# check 2x + 5y - z = 27
2*x2 + 5*y2 - 1*z2

27.000000000000004

<hr style="border:0.5px solid gray"> </hr>

### Equation #3

x + y = 4

2x + 2y = 8


What happens here and why?

In [13]:
#coeficients
A3 = np.array([[1,1],[2,2]])

#Requirement
B3 = np.array([[4],[8]])

In [14]:
# Solving the problem
X3 = np.linalg.inv(A3).dot(B3)
X3

LinAlgError: Singular matrix

**Conclusion:** The matrix A3 is a singular matrix, upon further investigation I found that Singular matrix means the determinent is zero which basically means it can not be reversed, so I checked the determinent with the "np.linalg.det" function and it gave me zero, therefore the matrix can not be reversed. 

In [15]:
# I checked the det using the numpy built in det method
det = np.linalg.det(A3)
det

0.0

**However**: I was not satisfied with this solution and I still wanted to try to solve it so I looked up ways to invert a singular square matrix and I found the following: 

**1. Stack overflow method that inverts a singular square matrix using the lstsq method:**

[Click here](https://stackoverflow.com/questions/13795682/numpy-error-singular-matrix) to go to that link. 


In [16]:
def inv(m):
    a, b = m.shape
    if a != b:
        raise ValueError("Only square matrices are invertible.")

    i = np.eye(a, a)
    return np.linalg.lstsq(m, i)[0]
inv(A3)

<ipython-input-16-69a7d7c470d1>:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  return np.linalg.lstsq(m, i)[0]


array([[0.1, 0.2],
       [0.1, 0.2]])

**2. I noticed that the result of the stack overflow method would be the same as if I transposed the matrix and divided by 10**

I tried googling a lot of math and understand why 10 exactly but I could not find the result I wanted. 

In [17]:
np.transpose(A3)/10

array([[0.1, 0.2],
       [0.1, 0.2]])

**3. I found another stack overflow link that inverts the singular square matrix using the [psuedo inverse](https://numpy.org/doc/stable/reference/generated/numpy.linalg.pinv.html) from numpy**

[Click here](https://stackoverflow.com/questions/52289379/invert-singular-matrix-on-python) to go to that link.

**Moore-Penrose Inverse Definition:** the psuedo inverse is also known in the math world as the Moore-Penrose inverse, which is a generalization of the matrix inverse when the matrix may not be invertible, it can be defined even when a matrix is not invertible and for this reason it is most widely used to complete a best fit solution to a linear equation that lacks a solution. 

In [18]:
inv = np.linalg.pinv(A3)
inv

array([[0.1, 0.2],
       [0.1, 0.2]])

In [19]:
# Solving the problem
X3 = np.linalg.pinv(A3).dot(B3)
X3

array([[2.],
       [2.]])

In [20]:
#Checking our results by plugging in the values
x3 = X3[0][0]
y3 = X3[1][0]

In [21]:
# check x + y = 4
1*x3 + 1*y3

3.9999999999999987

In [22]:
# check 2x + 2y = 8
2*x3 + 2*y3

7.999999999999997